### ISSUE TITLE
NOTABUG: Cloning of submodules via HTTPS instead of SSH

### ISSUE THREAD

**Issue by L0g4n** [solutionroute/hugo-smorg#2]
Hi,

in your `README` you say to clone the repo use the following command `git clone --recursive https://github.com/solutionroute/hugo-smorg.git`. So git tries to clone the submodules you have in `.gitmodules` but the repos you listed there are cloned via SSH, but fails of course then for me because i get permissions errors.

**EDIT**: Sorry, this is of course not a bug, i forgot that i only had my gitlab SSH key in my ssh-agent added and not my github SSH key 🤦‍♂️ . Still for simply cloning it would may be better to just clone via SSH because for 3rd party repos you do not have permission to write anyway. So you actually have no advantage from using SSH.

**Comment by solutionroute** [comment]
Hi, sorry for the delay in replying.  

I will update the submodules to use HTTPS; even those that I author - thank you so much for bringing this to my attention!

**Comment by solutionroute** [comment]
Updated and tests ok on my side, thanks again for the heads up. 👍
