### ISSUE TITLE
Hugo Themes Demo Site has broken navbar links

### ISSUE THREAD

**Issue by j1mc** [solutionroute/hugo-smorg#3]
To reproduce, go to:  https://themes.gohugo.io/theme/hugo-smorg/ and click on the links in the heading (e.g., About, Projects, Blog), and you'll get a (rather nice looking) 404 error.

The links work if you go to:

1. https://themes.gohugo.io/theme/hugo-smorg/about
1. https://themes.gohugo.io/theme/hugo-smorg/project
1. https://themes.gohugo.io/theme/hugo-smorg/post

I think you'll need to adjust the navbar templates to get this to work.

**Comment by solutionroute** [comment]
Thanks for the report; I'd noticed this myself a couple of days ago and corrected the issue (I believe); I went through the templates looking for hrefs that needed to be alerted with the absURL filter and nav.html certainly was updated.

I see the theme site was updated and would have expected the changes to make their way; will dig into this a bit more. Thanks.

**Comment by solutionroute** [comment]
Solved; I was looking at the code and scratching my head but the problem was in the exampleSite config.yaml - leading "/" in the menu definitions  i.e. /post/ is a definite no-no that slipped in right at the start.

Thanks very much for pointing this out.
