### ISSUE TITLE
Error: Failed to process archetype file themes/hugo-smorg/archetypes/default.md

### ISSUE THREAD

**Issue by tordanpersson** [solutionroute/hugo-smorg#6]
When I try to create a new file: 

hugo new kontakt/kontakt-formular.md

I get the error:

Error: Failed to process archetype file "/Users/svennebanan/Documents/ABCLillaBegravningsbyrån/appernetic-hugo-project/themes/hugo-smorg/archetypes/default.md": template: default:2:19: executing "default" at <.Name>: can't evaluate field Name in type create.ArchetypeFileData

If I change hugo-smorg/archetypes/default.md:

title: "{{ replace .Name "-" " " | title }}"

to:

title: "{{ replace .TranslationBaseName "-" " " | title }}"

it works. 

I haven't investigated it further, I'm happy I got it working for now. I am using Hugo v0.34  

Realy nice theme by the way.

I have put all my customizations and bugfixes in the layout folder and archetypes folder overriding the theme. So no PR yet.

**Comment by solutionroute** [comment]
Thanks for the feedback on this issue and the kind words. I have to admit I have not looked very closely at the internationalization features Hugo offered but am willing to do so. 

I'll put some conditional logic into the archetype so failures like that will not occur.

**Comment by solutionroute** [comment]
Fixed using TranslationBaseName per your note. At one point .Name must have been exposed in some version by Hugo as I've not run into this before but as .Name isn't documented the change is definitely needed. Thanks! Closes #6

https://gohugo.io/variables/files/#prose

**Comment by StefanHermannBerlin** [comment]
I had the same issue. My file archetypes/default.md used .Name and it seems it cannot handle file names with a colon. The following default.md content solved the issue for me:

`---
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
draft: true
---

`

**Comment by solutionroute** [comment]
Thank you; sorry I have been away, I'll get this updated and testedb this
evening - appreciate your time on this.

Mike
